- ros_topic_name: "lidar"
  gz_topic_name: "lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 1       # Default 10 if qos_profile is empty, otherwise not set by default
  publisher_queue: 1        # Default 10 if qos_profile is empty, otherwise not set by default
  lazy: false                # Default "false"
  direction: GZ_TO_ROS  # Default "BIDIRECTIONAL" - Bridge both directions
    # "GZ_TO_ROS" - Bridge Gz topic to ROS
  # "ROS_TO_GZ" - Bridge ROS topic to Gz
  qos_profile: SENSOR_DATA  # Default is a default-constructed QoS with appropriate queue size